uv run pyinstaller ./src/main.py ^
    --name anonify ^
    --onefile ^
    --noconsole ^
    --icon .\assets\icon.ico ^
    --splash .\assets\splash.png ^
    --noupx ^
    --collect-all openvino ^
    --add-data .\models\yolo11n_openvino_model\yolo11n.bin:.\models\yolo11n_openvino_model ^
    --add-data .\models\yolo11n_openvino_model\yolo11n.xml:.\models\yolo11n_openvino_model ^
    --add-data .\models\yolo11n_openvino_model\metadata.yaml:.\models\yolo11n_openvino_model
